---
title: "Dirichlet Bayes"
author: "CJR"
date: "2023-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(brms)
library(tictoc)
library(DirichletReg)
```


```{r}
FA <- read_csv(here("analysis/data/derived_data/FA_all_tidied.csv"))|>
  select(where(~ any(. != 0)))


FA_groups_per <- FA|> 
  mutate(total_FA = rowSums(across(4:40)))|>
  mutate(across(4:40, ~./total_FA), .keep = "unused")|>
  rowwise()|>
  mutate(MUFA = sum(c_across(contains(":1"))),
         #MUFA_16 = sum(c_across(contains("16:1"))),
         #MUFA_18 = sum(c_across(contains("18:1"))),
         SAFA = sum(c_across(c(matches(":0"),-matches("i-"),-c(`22:0`, `24:0`,`23:0`)))),
         LSAFA = sum(c_across(c(`22:0`, `24:0`,`23:0`))),
         brFA = sum(c_across(contains("i-"))),
         algal_16PUFA = sum(c_across(c(`16:2w7`,`16:3w4`, `16:4w1`,`16:3w3`,`16:4w3`,`16:2w6`))),
         HUFA = sum(c_across(c(`20:5w3`,`22:6w3`,`22:5w3`))),
         LIN_EDA = sum(c_across(c(`18:2w6`,`20:2w6`))), #LIN can be elongated to EDA
         SDA = `18:4w3`,
         ALA = `18:3w3`,
         ARA = `20:4w6`,
         GLA = `18:3w6`, .keep = "all", .after = Type)|>
  select(Site,Taxon, Type, MUFA, SAFA,LSAFA,brFA,algal_16PUFA,
         HUFA,LIN_EDA,SDA,ALA,ARA,GLA, Canopy_Cover_per, NO3_ug.L, EcoRegion)|>
  mutate(sum_fa_per = rowSums(across(4:14)), .before = MUFA)|>
  filter(Type == "Periphyton")|>
  select(-Type,-Taxon,-Site)|>
  mutate(across(2:12, ~./sum_fa_per))|>
  select(-sum_fa_per)|>ungroup()|>
  mutate(scaled_no3 = scale(NO3_ug.L)[,1],
         scaled_canopy = scale(Canopy_Cover_per)[,1]) #scaling helps reg models

```




```{r burkner example}
bind <- function(...) cbind(...)




make_stancode(cbind(MUFA, SAFA,LSAFA,brFA,diatom_16PUFA,
                    green_16PUFA, that_fa, EPA,DHA,DPA,LIN,SDA,ALA,ARA,GLA) ~ Canopy_Cover_per, FA_groups_per, dirichlet)


tic()
fit2 <- brm(cbind(MUFA, SAFA,LSAFA,brFA,algal_16PUFA,
         HUFA,LIN_EDA,SDA,ALA,ARA,GLA) ~ scaled_canopy+scaled_no3, data=FA_groups_per, dirichlet())
toc()

tic()
fit3 <- brm(cbind(MUFA, SAFA,LSAFA,brFA,algal_16PUFA,
         HUFA,LIN_EDA,SDA,ALA,ARA,GLA) ~ scaled_canopy+scaled_no3+EcoRegion, data=FA_groups_per, gaussian())
toc()
```

```{r}
summary(fit)
pp_check(fit, resp="EPA")

blah <- posterior_predict(fit)
ds_yrep1 <- FA_groups_per %>% 
  #select(log_weight, log_gest_c) %>% 
  add_predicted_draws(fit)

blah <-ds_yrep1 %>% mutate(.draw = 1)

ds_yrep1 |>
  filter(.draw<200, .category == "EPA")|>
  ggplot(aes(.prediction, group = .draw)) + 
  geom_density(alpha = 0.2, aes(color = "y_rep")) + 
  geom_density(data = ds_yrep1 %>% filter(.draw == 1), 
               aes(x = EPA)) + 
  theme_bw(base_size = 16)

summed_df <- ds_yrep1|>filter(.draw<=100)|>group_by(.category)|>
  mutate(med_pred = median(.prediction),
         pred_95 = quantile(.prediction, 0.95),
         pred_05 = quantile(.prediction, 0.05))

ggplot()+
  geom_line(data = summed_df,aes(x = Canopy_Cover_per, y = med_pred))+
  geom_line(data = summed_df,aes(x = Canopy_Cover_per, y = pred_95), linetype = "dashed")+
  geom_line(data = summed_df,aes(x = Canopy_Cover_per, y = pred_05), linetype = "dashed")+
  facet_wrap(.~.category, scales = "free")

```


```{r}
FA_analysis <- FA_groups_per
FA_analysis$Y <- DR_data(FA_analysis[,1:11])
dr_1 <- DirichReg(Y ~ scaled_canopy+scaled_no3|scaled_canopy+scaled_no3, FA_analysis, model = "alternative")
dr_2 <- DirichReg(Y ~ 1|scaled_canopy+scaled_no3, FA_analysis, model = "alternative")
dr_3 <- DirichReg(Y ~ 1, FA_analysis, model = "alternative")
dr_4 <- DirichReg(Y ~ scaled_canopy, FA_analysis, model = "alternative")
dr_5 <- DirichReg(Y ~ scaled_no3, FA_analysis, model = "alternative")
dr_6 <- DirichReg(Y ~ scaled_canopy+scaled_no3, FA_analysis, model = "alternative")

anova(dr_1,dr_2,dr_3,dr_4,dr_5)

summary(dr_1)
new_data <- expand_grid(scaled_canopy = seq(0,100, by = 10),
                        scaled_no3 = seq(0,460, by = 10))|>
  filter(NO3_ug.L %in% c(10,200,460))

new_data <- expand_grid(scaled_canopy = seq(-2,2, by = 0.2),
                        scaled_no3 = seq(-1,2, by = 0.2))|>
  mutate(scaled_no3 = as_factor(scaled_no3))|>
  filter(scaled_no3 %in% c(-1.0,0.4,1.8))|>mutate(scaled_no3 = as.numeric(as.character(scaled_no3)))
dir_confint <- confint(dr_1)
dir_fitted <- predict(dr_6,newdata=new_data)
colnames(dir_fitted)<-colnames(FA_analysis$Y)
dir_fitted2 <- bind_cols(dir_fitted, new_data)|>
  pivot_longer(c(1:11),values_to = "predicted", names_to = "FA")|>
  mutate(FA = as_factor(FA), scaled_no3 = as_factor(scaled_no3))

ggplot()+
  geom_line(data = dir_fitted2, aes(x = scaled_canopy, y = predicted, linetype = scaled_no3))+
  geom_point(data=FA_groups_per|>pivot_longer(c(1:11), values_to = "value", names_to = "FA"), aes(x = scaled_canopy, y = value, color = scaled_no3))+
  facet_wrap(.~FA, scales = "free")
  
dir_confint$ci[[1]]
```

```{r}
blah <- emmeans(fit)

```
